# Generated by Django 5.0.1 on 2024-03-16 17:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0007_alter_feedback_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('subject', models.CharField(max_length=30)),
                ('message', models.TextField()),
                ('date', models.DateField(default=datetime.date(2024, 3, 16))),
            ],
            options={
                'db_table': 'inquiry',
            },
        ),
        migrations.AlterField(
            model_name='feedback',
            name='date',
            field=models.DateField(default=datetime.date(2024, 3, 16)),
        ),
    ]
