# Generated by Django 5.0.1 on 2024-03-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
