# Generated by Django 5.0.1 on 2024-03-24 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0020_delete_order_alter_feedback_date_alter_inquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('address', models.TextField()),
                ('details', models.TextField()),
                ('total', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'order',
            },
        ),
    ]
