# Generated by Django 5.0.1 on 2024-03-25 18:46

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0022_order_date_alter_feedback_date_alter_inquiry_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
                ('mobile', models.BigIntegerField()),
                ('total', models.CharField(max_length=10)),
                ('pay_type', models.CharField(max_length=20)),
                ('date', models.DateField(default=datetime.date(2024, 3, 26))),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customer.order')),
            ],
            options={
                'db_table': 'payment',
            },
        ),
    ]
