# Generated by Django 5.0.1 on 2024-03-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0023_payment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
    ]
