# Generated by Django 5.0.1 on 2024-04-16 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0032_order_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-date']},
        ),
    ]
