# Generated by Django 5.0.1 on 2024-03-14 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='discription',
            new_name='description',
        ),
    ]
