# Generated by Django 5.0.1 on 2024-03-16 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0006_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
