# Generated by Django 5.0.1 on 2024-03-18 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0008_alter_product_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deliveryboy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('db_fname', models.CharField(max_length=30)),
                ('db_lname', models.CharField(max_length=30)),
                ('mobile', models.BigIntegerField()),
                ('email', models.CharField(max_length=50)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'deliveryboy',
            },
        ),
    ]
