# Generated by Django 5.0.1 on 2024-03-21 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0017_cart'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
