# Generated by Django 5.0.1 on 2024-03-22 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0018_delete_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_name',
            new_name='name',
        ),
    ]
