# Generated by Django 5.0.1 on 2024-03-23 08:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0021_alter_product_subcategory_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
