# Generated by Django 5.0.1 on 2024-04-17 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0022_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_category',
            name='category',
        ),
    ]
